---
application:
  name: "mstokyobot"
  project: "MsTokyo"
  organization: "QoveryCommunity"
  storage:
  - name: "MsTokyo"
    size: "2000"
    type: "hdd"
    mount_point: "/mnt/MsTokyo"
routers:
- name: "main-mstokyobot"
  routes:
  - application_name: "mstokyobot"
    paths:
    - "/*"
