---
application:
  name: "mstokyobot"
  project: "MsTokyo"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "MsTokyoBot"
  version: "11"
routers:
- name: "main-mstokyobot"
  routes:
  - application_name: "mstokyobot"
    paths:
    - "/*"
