---
application:
  name: "mstokyobot"
  project: "MsTokyo"
  organization: "QoveryCommunity"
  storage:
  - name: "mstokyo"
    size: "500"
    type: "hdd"
    mount_point: "/mnt/mstokyo"
databases:
- type: "POSTGRESQL"
  name: "mstokyodb"
  version: "11"
routers:
- name: "main-mstokyobot"
  routes:
  - application_name: "mstokyobot"
    paths:
    - "/*"
